#!/usr/bin/env python
# -*- coding: utf-8 -*-

client_list = [	
'Twitter For Android',	
'Twitter For Iphone',	
'Twitter Web App',	
'Echobox Social',	
'Twittbot.Net',	
'Tweetcaster For Android',	
'Dlvr.It',	
'Tabtter Free',	
'Tweetdeck',	
'Dopeyuncle2',	
'Instagram',	
'Mobile Web (M2)',	
'Cheap Bots, Done Quick!',	
'Twitter For Ipad',	
'Twitter Web Client',	
'Facebook',	
'Wordpress.Com',	
'Ifttt',	
'Hootsuite Inc',	
'Google',	
'Plume For Android',	
'Twitcasting',	
'Tweetbot For Iοs',	
'Buffer',	
'Echofon',	
'Twitpane For Android',	
'Latermedia',	
'Sprout Social',	
'Ubersocial For Android',	
'Roltweet',	
'Micom',	
'The Social Jukebox',	
'デレステ公式',	
'Harian Ekonomi Neraca',	
'Jpnn News Update',	
'Lsisi.Id',	
'Bmkg',	
'Flexi Recipes',	
'Tween',	
'Detikcommunity',	
'Twitter Media Studio',	
'Kontan Tweet',	
'Jawapos.Com Auto Tweet',	
'Foursquare',	
'Twitterrific For Ios',	
'Alinea.Id',	
'Sender Dmenfess',	
'Rlthingy',	
'Investor Daily',	
'Peing',	
'Twitter For Visioner',	
'Ask.Fm',	
'Smarterqueue',	
'Okezonemobile',	
'Flamingo For Android',	
'Rkymtnnaturalstweets',	
'Hooppy',	
'Majalah Samudra',	
'Mailchimp',	
'Foursquare Swarm',	
'Idntimes Live Blog',	
'Kompasekonomi',	
'Socialbee.Io V2',	
'Twitpaneplus',	
'Coschedule',	
'Everycurd',	
'Blog2Social App',	
'Oneup App',	
'Sharjah Airport',	
'Playstation(R)4',	
'アイドルマスター シンデレラガールズ公式',	
'Rmol',	
'Tweetbot For Mac',	
'Bolabanget Idn Broadcaster',	
'Ms-Room.Com',	
'Microsoft Power Platform',	
'_Beautytalk_',	
'Gatra.Com',	
'Sociabuzzplatform',	
'Beritasatu',	
'Blogsderecetas Twitteador',	
'Blogdokter',	
'Manadopost',	
'Beauthingy',	
'Ciee Menfessnya Di Nyampahkuy',	
'Popmamaautomation',	
'Yelp',	
'Pemilu_Org',	
'Bbcccnn',	
'App Android Toos',	
'Just For Your Information',	
'Sociomedio Pro Post 4',	
'Bitly',	
'Indozone',	
'Topculinario',	
'Mirasahid.Com',
'Kabartangsel.Com',	
'Shopee_Id',	
'Talon Android',	
'Echofon Android',	
'Mention',	
'Tweecha Lite',	
'Socialoomph',	
'Newpreloved',	
'Boxfresh',	
'Revive Social App',	
'Symbiosispapers',	
'Social Media Publisher App', 	
'Оwly',	
'Twitter For Advertisers',	
'Bot Libre!',	
'Radarpena.Id',	
'Gr33Nbot',	
'Foodfluencer',	
'Inilah.Com Auto Post Tweet V2',	
'Berita7 Id',	
'Beritakini.Co',
'Find Lat Lng',	
'Twitterotomotif',	
'Citcuit',	
'Sumall',	
'Indopolitika.Com',	
'Askmenfess2',	
'Postcron App',	
'Auto Base Rp',	
'グランブルー ファンタジー',	
'Animalfess2',	
'Threadreaderapp',	
'Grouptweet',	
'Dogtrack_Oficial',	
'Ivosights - Sociomile',	
'Baca Utas',	
'Smart Post App',	
'Bukalapak',	
'Sender Areajulid',	
'Big Business',	
'Ivoox Id',	
'Tweet Old Post',	
'Sloth_Diggs',	
'Deeptouk',	
'Zapier.Com',	
'Twidere For Android (Deprecated)',	
'Gravity Forever',	
'Startup Bulletin',	
'Browsertoi',	
'Base Kece 😎',	
'Eastrp',	
'Onlyrpe',	
'Majestirc',	
'@Rpxbase',	
'Rplworld',	
'Bucinfess',	
'Tweetotimatispositif',	
'Tweetings For Android',	
'Conversocial',	
'Iweightlossnow',	
'Todaysmathematics',	
'Onlypultcom',	
'Hubspot',	
'Social Web Suite',	
'Akasatanahama_Bot',	
'Nextscripts Batasnegeri',	
'Businessnews Indonesia',	
'Pengadaannet',	
'Automationpostpopbela',	
'Zendesk',	
'Ngalamfess',	
'Inipastidotcom',	
'Infoblaze Indonesia',	
'Infoblaze Southeast Asia',	
'Wiedza Ogólna',	
'Babe - Baca Berita Indonesia', 	
'Ppcm Twitter Bots (Labnol)',	
'Stamped.Io',	
'Cyberfeds News Feed',	
'Zarobitchany',	
'Socialflow',	
'Theworld For Ios',	
'Techgyver',	
'Yorufukurou',	
'Cal Fact Check',	
'Berita-Sulsel',	
'Sprinklr',	
'Trubus Indonesia',	
'Autopost Arah',	
'Twitter For Mac',	
'Mydamnstuffs',	
'Twit Berita',	
'Autopush She',	
'Wday.Ru',	
'Koreanthingy',	
'@Indolinearcom',	
'Blogger Perempuan',	
'Quranindex',	
'Mytweetbuddy19045',	
'Revpal',	
'Thejakartaglobe',	
'Foodbloggermania.It',	
'Chapelurebot_App',	
'Shuttlerock - Bluebird',	
'Gambiste',	
'Nintendo Switch Share',	
'Seolit Publisher',	
'Giuseppe.Salone@Gmail.Com',	
'Jeketi Feeds',	
'Metricool',	
'Freegle',	
'Kai Bangkit',	
'Missinglettr',	
'Islamidotcoautoshare',	
'Ubersocial For Iphone',	
'Katadata News',	
'Automated V2',	
'2017_Ebooks',	
'Contentposting',	
'Threader_Client',	
'Avfc News And Gossip',	
'Wp Tweet-Machine',	
'Bacapesan',	
'Leefnugezonder.Be',	
'Tom Wilson',	
'Ted Wilson',	
'Planable',	
'Evergreen Post Tweeter',	
'Sociomedio Pro Post 2',	
'Tim Wilson',	
'Tagar News',	
'Doktersehat',	
'Twibble.Io',	
'@Collegemenfess',	
'Empat Sajak Bot',	
'Japanfess',	
'Fenix 2',	
'Rns Alert',	
'Medcom_Api',	
'Auto Post Strategi.Id',	
'Nawacita_App',	
'Banjarbase',	
'Hipchicagobot',	
'Rmoljakarta',	
'Amplifr',	
'Prokabar.Com',	
'The Tweeted Times',	
'Beritasampit.Id'
]	